import { connectMongodb } from '../../../core/db/index.js'
import mongoose from 'mongoose'
import { log } from '../../../core/log/index.js'
import { ProductModel } from '../products.schema.js'
import { ShopModel } from '../../shops/shops.schema.js'
import { DefaultProductModel } from '../../default-products/default-products.schema.js'
import { createProductSrvc } from '../products.service.js'

export const seedProducts = async () => {
	try {
		log({ message: 'Starting products seed script...', level: 'info' })

		// Check Shops
		const shops = await ShopModel.find({}).lean()
		if (shops.length === 0) {
			log({ message: 'No shops found. Please run shops seed first.', level: 'warn' })
			return
		}

		// Check Default Products
		const defaultProducts = await DefaultProductModel.find({}).lean()
		if (defaultProducts.length === 0) {
			log({ message: 'No default products found.', level: 'warn' })
			return
		}

		// Clear existing products and indexes to avoid legacy index issues
		try {
			await ProductModel.collection.drop()
		} catch (e) {
			// Ignore error if collection does not exist
		}
		// ensure indexes are created
		await ProductModel.ensureIndexes()
		log({ message: 'Cleared existing products and rebuilt indexes.', level: 'info' })

		let count = 0

		for (const shop of shops) {
			// Pick 5-8 random default products
			const shuffled = [...defaultProducts].sort(() => 0.5 - Math.random())
			const selected = shuffled.slice(0, Math.floor(Math.random() * 4) + 5)

			for (const dp of selected) {
				// Generate a slug for default product if missing (handling potential bad seed data)
				const dpSlug =
					dp.slug ||
					(dp.name?.en || 'product')
						.toLowerCase()
						.replace(/\s+/g, '-')
						.replace(/[^\w-]+/g, '')

				// Ensure name object is valid
				const validName = {
					en: dp.name?.en || 'Unknown Product',
					tn_en: dp.name?.tn_en || dp.name?.en || 'Unknown Product',
					tn_ar: dp.name?.tn_ar || ''
				}

				const productData = {
					shop: {
						_id: shop._id,
						owner: shop.owner,
						name: shop.name,
						slug: shop.slug,
						address: shop.address,
						location: shop.location
					},
					defaultProduct: {
						_id: dp._id,
						slug: dpSlug,
						name: validName,
						images: {
							thumbnail: {
								url: 'https://placehold.co/200'
							}
						}
					},
					name: validName.en,
					// Slug for product will be generated by plugin from 'name' if omitted, or we can provide base
					price: {
						value: {
							tnd: parseFloat((Math.random() * 50 + 5).toFixed(2))
						},
						unit: { name: 'KG', min: 1 }
					},
					searchTerms: [...(dp.searchKeywords || []), ...shop.name.split(' ')],
					state: { code: 'active' },
					stock: {
						quantity: Math.floor(Math.random() * 100),
						minThreshold: 5
					},
					availability: {
						startDate: new Date()
					}
				}

				await createProductSrvc({ data: productData })
				count++
			}
		}

		log({ message: `Successfully seeded ${count} products.`, level: 'success' })
	} catch (e) {
		log({ message: 'Error seeding products', error: e.message, level: 'error' })
	}
}

const processScript = async () => {
	log({ message: `running ${scriptFilename}`, level: 'info' })
	log({ message: 'Starting users seed script...', level: 'info' })
	// Create each owner
	for (const userData of users) {
		const signedupUser = await createUserSrvc(userData)
		await createAuthSrvc({ user: signedupUser, password: userData.password })
		log({ message: `Created user: ${userData.slug}`, level: 'info' })
	}

	log({ message: 'Owners seed completed successfully', level: 'success' })
	return { success: true, message: 'Owners seeded successfully' }
}

async function run() {
	try {
		if (config.NODE_ENV === 'production') throw new Error('script is not allowed to run in production environment')
		await mongoose.connect(config.db.mongodb.uri, {})
		console.log(`Connected to MongoDB: ${config.db.mongodb.uri}`)
		await processScript()
	} catch (error) {
		console.error('script error:', error)
	} finally {
		await mongoose.connection.close()
		console.log('MongoDB connection closed')
	}
}
run()
